alter table if exists public."Account"
  add column if not exists email_verified_at timestamp(0);

create table if not exists public.account_email_verification_otp (
  otp_id bigint generated by default as identity primary key,
  account_id bigint not null references public."Account"(account_id),
  code_hash text not null,
  expires_at timestamp(0) not null,
  attempts integer not null default 0,
  consumed_at timestamp(0),
  created_at timestamp(0) not null default now()
);

create index if not exists idx_account_email_verification_otp_account_id
  on public.account_email_verification_otp(account_id);

create index if not exists idx_account_email_verification_otp_expires_at
  on public.account_email_verification_otp(expires_at);
